language: go
sudo: false

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else go get -t -v ./...; fi

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/acc2c57482e94b44f557
    on_success: change
    on_failure: always
    on_start: false
